### ISSUE TITLE
Can this firmware repository be packaged and updated independently?

### ISSUE THREAD

**Issue by YanceyChiew** [ophub/firmware#4]
Can it be updated independently of the armbian release image like the [`kernel`](https://github.com/ophub/kernel) repository?

Is there any corresponding plan or implementation?

**Comment by ophub** [comment]
This section is common to the official Armbian version. I have not made any changes, but have independently saved the firmware used by the current device. Do you have any good update suggestions?

**Comment by YanceyChiew** [comment]
I noticed that in the [amlogic-s9xxx-armbian](https://github.com/ophub/amlogic-s9xxx-armbian) repository, armbian-firmware.deb was first built with the [official armbian release](https://github.com/armbian/build) and then lib/fireware was customized through the [`rebuild`](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/rebuild) script.

[armbian-firmware.deb control file](https://github.com/armbian/build/blob/879805a520eaa4c35fe90cc400e224940ef32bcc/lib/functions/compilation/packages/firmware-deb.sh#L58-L77) :
```bash
	mkdir -p DEBIAN
	# @TODO: rpardini: this needs Conflicts: with the standard Ubuntu/Debian linux-firmware packages and other firmware pkgs in Debian
	cat <<- END > DEBIAN/control
		Package: armbian-firmware${FULL}
		Version: ${artifact_version}
		Architecture: all
		Maintainer: $MAINTAINER <$MAINTAINERMAIL>
		Installed-Size: 1
		Conflicts: linux-firmware, firmware-brcm80211, firmware-ralink, firmware-samsung, firmware-realtek, armbian-firmware${REPLACE}${extra_conflicts_comma}
		Provides: linux-firmware, firmware-brcm80211, firmware-ralink, firmware-samsung, firmware-realtek, armbian-firmware${REPLACE}${extra_conflicts_comma}
		Section: kernel
		Priority: optional
		Description: Armbian - Linux firmware${FULL}
	END

	cd "${fw_temp_dir}" || exit_with_error "can't change directory"

	# package, directly to DEB_STORAGE; full version might be very big for tmpfs.
	display_alert "Building firmware package" "armbian-firmware${FULL}" "info"
	fakeroot_dpkg_deb_build "armbian-firmware${FULL}" "${DEB_STORAGE}"

```

---

Therefore, if we want the firmware to be updated independently, there are two ways to package it:
 - After the system that has been successfully built is started, repack the changed firmware into a deb file through the `dpkg-repack armbian-firmware` command, and then distribute it.
 - According to the control file quoted above, directly use this repository to package a new `armbian-firmware.deb`. This can also be customized by adding postinst scripts, such as [generating random mac addresses](https://github.com/ophub/amlogic-s9xxx-armbian/blob/2ba899e179170d2c0e24a61cef4e0dcf6fda0a8d/rebuild#L903-L923) for _each_ machine.

I think the latter is more reasonable, and it is also beneficial to use github action to automatically release.

**Comment by ucsoom** [comment]
I think the latter is more reasonable, and it is also beneficial to use github action to automatically release.
